# Generated by Django 5.0 on 2024-11-24 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id_symptom', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('symptom_type', models.CharField(choices=[('general', 'Général'), ('ovulation', 'Ovulation'), ('menstrual', 'Menstruel')], default='general', max_length=10)),
                ('category', models.CharField(choices=[('physique', 'Physique'), ('emotion', 'Émotion'), ('humeur', 'Humeur')], default='physique', max_length=10)),
            ],
            options={
                'db_table': 'symptom',
            },
        ),
        migrations.CreateModel(
            name='Woman',
            fields=[
                ('id_woman', models.AutoField(primary_key=True, serialize=False)),
                ('average_cycle_length', models.IntegerField(default=28)),
                ('average_menstruation_duration', models.IntegerField(default=5)),
                ('last_period_date', models.DateField(blank=True, null=True)),
                ('regle_type', models.CharField(choices=[('regulier', 'Régulier'), ('irregulier', 'Irrégulier')], default='regulier', max_length=50)),
                ('symptoms', models.ManyToManyField(related_name='symptoms', to='menstruation.symptom')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='woman', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'woman',
            },
        ),
        migrations.CreateModel(
            name='SymptomLinkWoman',
            fields=[
                ('id_symptom_link', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('symptoms', models.ManyToManyField(related_name='symptoms_link_date', to='menstruation.symptom')),
                ('woman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptoms_link_date', to='menstruation.woman')),
            ],
            options={
                'db_table': 'symptom_link',
            },
        ),
        migrations.CreateModel(
            name='Ovulation',
            fields=[
                ('id_ovulation', models.AutoField(primary_key=True, serialize=False)),
                ('predicted_ovulation_date', models.DateField()),
                ('fertility_window_start', models.DateField()),
                ('fertility_window_end', models.DateField()),
                ('symptoms', models.ManyToManyField(blank=True, related_name='ovulation_symptoms', to='menstruation.symptom')),
                ('woman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ovulations', to='menstruation.woman')),
            ],
            options={
                'db_table': 'ovulation',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id_notification', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('woman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='menstruation.woman')),
            ],
            options={
                'db_table': 'notification',
            },
        ),
        migrations.CreateModel(
            name='Menstruation',
            fields=[
                ('id_menstruation', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('woman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menstruations', to='menstruation.woman')),
            ],
            options={
                'db_table': 'menstruation',
            },
        ),
    ]
