# Generated by Django 5.0 on 2024-11-24 10:27

import apps.forum.models
import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileDF',
            fields=[
                ('id_file', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='forum/message_files/')),
            ],
            options={
                'db_table': 'file_message',
            },
        ),
        migrations.CreateModel(
            name='ImageDF',
            fields=[
                ('id_image', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='forum/message_images/')),
            ],
            options={
                'db_table': 'image_message',
            },
        ),
        migrations.CreateModel(
            name='DiscussionForum',
            fields=[
                ('id_discussion_forum', models.AutoField(primary_key=True, serialize=False)),
                ('profile', models.ImageField(default='forum/profiles/groupes/default.jpg', upload_to='forum/profiles/groupes/')),
                ('created_at', models.DateTimeField(default=apps.forum.models.default_created_at)),
                ('membres', models.ManyToManyField(related_name='discussionsF', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'discussionforum',
            },
        ),
        migrations.CreateModel(
            name='MessageDF',
            fields=[
                ('id_messageDF', models.AutoField(primary_key=True, serialize=False)),
                ('contenu', models.TextField(blank=True, null=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=apps.forum.models.default_created_at)),
                ('discussionF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='forum.discussionforum')),
                ('dislikes', models.ManyToManyField(related_name='messageDF_dislikes', to=settings.AUTH_USER_MODEL)),
                ('files', models.ManyToManyField(related_name='messageDF', to='forum.filedf')),
                ('images', models.ManyToManyField(related_name='messageDF', to='forum.imagedf')),
                ('likes', models.ManyToManyField(related_name='messageDF_likes', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'message',
            },
        ),
        migrations.CreateModel(
            name='PublicationForum',
            fields=[
                ('id_publication_forum', models.AutoField(primary_key=True, serialize=False)),
                ('contenu', models.TextField()),
                ('is_anonymous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 11, 24, 10, 27, 53, 164444, tzinfo=datetime.timezone.utc))),
                ('dislikes', models.ManyToManyField(related_name='publication_dislike', to=settings.AUTH_USER_MODEL)),
                ('files', models.ManyToManyField(related_name='publicationF', to='forum.filedf')),
                ('images', models.ManyToManyField(related_name='publicationF', to='forum.imagedf')),
                ('likes', models.ManyToManyField(related_name='publication_like', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicationF', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'publication_forum',
            },
        ),
        migrations.AddField(
            model_name='discussionforum',
            name='publicationF',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='forum.publicationforum'),
        ),
    ]
