# Generated by Django 5.0 on 2024-11-24 13:38

import apps.forum.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedf',
            name='file',
            field=models.FileField(upload_to='forum/filess/'),
        ),
        migrations.AlterField(
            model_name='imagedf',
            name='image',
            field=models.ImageField(upload_to='forum/images/'),
        ),
        migrations.AlterField(
            model_name='publicationforum',
            name='created_at',
            field=models.DateTimeField(default=apps.forum.models.default_created_at),
        ),
        migrations.AlterModelTable(
            name='filedf',
            table='file_forum',
        ),
        migrations.AlterModelTable(
            name='imagedf',
            table='image_forum',
        ),
    ]
