# Generated by Django 5.0 on 2024-11-24 10:27

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id_conversation', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 11, 24, 13, 27, 53, 184075, tzinfo=datetime.timezone.utc))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'conversationChat',
            },
        ),
        migrations.CreateModel(
            name='MessageChat',
            fields=[
                ('id_message_chat', models.AutoField(primary_key=True, serialize=False)),
                ('contenu', models.CharField(max_length=250)),
                ('from_user', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 11, 24, 13, 27, 53, 184075, tzinfo=datetime.timezone.utc))),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.conversation')),
            ],
            options={
                'db_table': 'messageChat',
            },
        ),
    ]
