# Generated by Django 5.0 on 2024-11-24 18:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 24, 21, 23, 15, 8911, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='messagechat',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 24, 21, 23, 15, 8911, tzinfo=datetime.timezone.utc)),
        ),
    ]
