# Generated by Django 5.0 on 2024-11-27 05:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_alter_conversation_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 27, 8, 42, 37, 97966, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='messagechat',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 27, 8, 42, 37, 97966, tzinfo=datetime.timezone.utc)),
        ),
    ]
